/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaixaTermicaRouteImport } from './routes/caixa-termica'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TutorIndexRouteImport } from './routes/tutor.index'
import { Route as TutorAgendaRouteImport } from './routes/tutor.agenda'
import { Route as TutorAssinaturaRouteImport } from './routes/tutor.assinatura'
import { Route as TutorPetsRouteImport } from './routes/tutor.pets'
import { Route as TutorProntuarioRouteImport } from './routes/tutor.prontuario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaTermicaRoute = CaixaTermicaRouteImport.update({
  id: '/caixa-termica',
  path: '/caixa-termica',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRoute,
} as any)
const TutorAgendaRoute = TutorAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => TutorRoute,
} as any)
const TutorAssinaturaRoute = TutorAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => TutorRoute,
} as any)
const TutorPetsRoute = TutorPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => TutorRoute,
} as any)
const TutorProntuarioRoute = TutorProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => TutorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixa-termica': typeof CaixaTermicaRoute
  '/prontuario': typeof ProntuarioRoute
  '/tutor': typeof TutorRouteWithChildren
  '/tutor/agenda': typeof TutorAgendaRoute
  '/tutor/assinatura': typeof TutorAssinaturaRoute
  '/tutor/pets': typeof TutorPetsRoute
  '/tutor/prontuario': typeof TutorProntuarioRoute
  '/tutor/': typeof TutorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixa-termica': typeof CaixaTermicaRoute
  '/prontuario': typeof ProntuarioRoute
  '/tutor/agenda': typeof TutorAgendaRoute
  '/tutor/assinatura': typeof TutorAssinaturaRoute
  '/tutor/pets': typeof TutorPetsRoute
  '/tutor/prontuario': typeof TutorProntuarioRoute
  '/tutor': typeof TutorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixa-termica': typeof CaixaTermicaRoute
  '/prontuario': typeof ProntuarioRoute
  '/tutor': typeof TutorRouteWithChildren
  '/tutor/agenda': typeof TutorAgendaRoute
  '/tutor/assinatura': typeof TutorAssinaturaRoute
  '/tutor/pets': typeof TutorPetsRoute
  '/tutor/prontuario': typeof TutorProntuarioRoute
  '/tutor/': typeof TutorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caixa-termica'
    | '/prontuario'
    | '/tutor'
    | '/tutor/agenda'
    | '/tutor/assinatura'
    | '/tutor/pets'
    | '/tutor/prontuario'
    | '/tutor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caixa-termica'
    | '/prontuario'
    | '/tutor/agenda'
    | '/tutor/assinatura'
    | '/tutor/pets'
    | '/tutor/prontuario'
    | '/tutor'
  id:
    | '__root__'
    | '/'
    | '/caixa-termica'
    | '/prontuario'
    | '/tutor'
    | '/tutor/agenda'
    | '/tutor/assinatura'
    | '/tutor/pets'
    | '/tutor/prontuario'
    | '/tutor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixaTermicaRoute: typeof CaixaTermicaRoute
  ProntuarioRoute: typeof ProntuarioRoute
  TutorRoute: typeof TutorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa-termica': {
      id: '/caixa-termica'
      path: '/caixa-termica'
      fullPath: '/caixa-termica'
      preLoaderRoute: typeof CaixaTermicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/agenda': {
      id: '/tutor/agenda'
      path: '/agenda'
      fullPath: '/tutor/agenda'
      preLoaderRoute: typeof TutorAgendaRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/assinatura': {
      id: '/tutor/assinatura'
      path: '/assinatura'
      fullPath: '/tutor/assinatura'
      preLoaderRoute: typeof TutorAssinaturaRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/pets': {
      id: '/tutor/pets'
      path: '/pets'
      fullPath: '/tutor/pets'
      preLoaderRoute: typeof TutorPetsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/prontuario': {
      id: '/tutor/prontuario'
      path: '/prontuario'
      fullPath: '/tutor/prontuario'
      preLoaderRoute: typeof TutorProntuarioRouteImport
      parentRoute: typeof TutorRoute
    }
  }
}

interface TutorRouteChildren {
  TutorAgendaRoute: typeof TutorAgendaRoute
  TutorAssinaturaRoute: typeof TutorAssinaturaRoute
  TutorPetsRoute: typeof TutorPetsRoute
  TutorProntuarioRoute: typeof TutorProntuarioRoute
  TutorIndexRoute: typeof TutorIndexRoute
}

const TutorRouteChildren: TutorRouteChildren = {
  TutorAgendaRoute: TutorAgendaRoute,
  TutorAssinaturaRoute: TutorAssinaturaRoute,
  TutorPetsRoute: TutorPetsRoute,
  TutorProntuarioRoute: TutorProntuarioRoute,
  TutorIndexRoute: TutorIndexRoute,
}

const TutorRouteWithChildren = TutorRoute._addFileChildren(TutorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixaTermicaRoute: CaixaTermicaRoute,
  ProntuarioRoute: ProntuarioRoute,
  TutorRoute: TutorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
