export enum UserRole {
  ADMIN_GERAL = 'ADMIN_GERAL',
  OPERADOR_ROTAS = 'OPERADOR_ROTAS',
  VET_RESPONSAVEL_TECNICO = 'VET_RESPONSAVEL_TECNICO',
  SUPORTE = 'SUPORTE',
  TUTOR = 'TUTOR',
  VET_FIELD = 'VET_FIELD',
}

export enum PetSpecies {
  CANINE = 'CANINE',
  FELINE = 'FELINE',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  SUSPENDED_OVERDUE = 'SUSPENDED_OVERDUE',
  CANCELED = 'CANCELED',
}

export enum AppointmentStatus {
  REQUESTED = 'REQUESTED',
  ROUTE_ASSIGNED = 'ROUTE_ASSIGNED',
  EN_ROUTE = 'EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  FAILED_ABSENT = 'FAILED_ABSENT',
}
